name: Doxygen GitHub Pages Deploy

# Action for building doxygen docs and deploying to GitHub Pages

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
          - main


jobs:
    generate-check-deploy:
        permissions:
            contents: write
            pages: write  

        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Setup ACT For Running Locally
            if: ${{ env.ACT }} 
            run: sudo apt-get update 

          - name: Install Doxygen
            shell: bash
            run: sudo apt-get install doxygen graphviz -y

          - name: Generate Documentation
            shell: bash
            run: doxygen >doxygen_output.txt 2>&1

          - name: Check Doxygen Output
            shell: bash
            run: | 
              cat doxygen_output.txt | grep --color -F -w "warning" | while read warning; do
                echo ::warning::${warning#$(pwd)}  # remove the leading absolute path
              done 

          - name: Create .nojekyll
            shell: bash
            run: touch docs/html/.nojekyll

          - name: Deploy to GitHub Pages # Does not run locally with act
            if: ${{ !env.ACT }} 
            uses: JamesIves/github-pages-deploy-action@v4
            with:
                folder: docs/html
                