name: Doxygen Deploy

# Action for building doxygen docs and deploying to GitHub Pages

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
          - main


jobs:
    generate:
        permissions:
            contents: write
        outputs:
            doxygen_warnings: ${{ steps.doxygen_output.outputs.warnings }}
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Setup ACT For Running Locally
            if: ${{ env.ACT }} 
            run: sudo apt-get update -q

          - name: Install Doxygen
            shell: bash
            run: sudo apt-get install doxygen graphviz -q -y

          - name: Generate Documentation
            shell: bash
            run: doxygen >doxygen_output.txt 2>&1

          - name: Save Doxygen Output
            id: doxygen_output
            shell: bash
            run: |
                echo "warnings<<EOF" >> "$GITHUB_OUTPUT"
                cat doxygen_output.txt >> "$GITHUB_OUTPUT"
                echo "EOF" >> "$GITHUB_OUTPUT"

          - name: Create .nojekyll
            shell: bash
            run: touch docs/html/.nojekyll

          - name: Upload Artifact
            uses: actions/upload-pages-artifact@v1
            with:
                name: github-pages
                path: docs/html

    deploy:
        needs: [generate]
        permissions:
            pages: write # To deploy to Pages
            id-token: write # To verify the deployment originates from an appropriate source
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
          - name: Deploy to GitHub Pages # Does not run locally with act
            id: deployment
            if: ${{ !env.ACT }} 
            uses: actions/deploy-pages@v2
                
    check-warnings:
        needs: [generate]
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
          - name: Retrieve Doxygen Output
            shell: bash
            run: |
                echo "${{ needs.generate.outputs.doxygen_warnings }}" > doxygen_output.txt

          - name: Check Doxygen Output
            shell: bash
            run: | 
                set +e  # Remove the -e flag to avoid aborting the script when grep doesn't find any warnings 

                warnings=$(cat doxygen_output.txt | grep -F -w "warning")
                if [ $? -eq  0 ]; then
                    cat doxygen_output.txt | grep -F -w "warning" | while read warning; do
                        echo ::error::${warning#$(pwd)}  # remove the leading absolute path
                    done

                    num_warnings=$(cat doxygen_output.txt | grep -F -w "warning" | wc -l)
                    echo "Doxygen run with $num_warnings warnings"
                    exit 1
                fi 

                echo "Doxygen run successfully"
                exit 0

    clean:
        needs: [deploy]
        # Run even if deploy job failed
        if: always() 
        runs-on: ubuntu-latest
        steps:
          - name: Delete Artifact
            uses: geekyeggo/delete-artifact@v2
            with:
                name: github-pages
